language: objective-c
osx_image: xcode7.3
xcode_sdk: 
    - iphonesimulator9.3
    - iphonesimulator9.2
xcode_project: RileyLink.xcodeproj
xcode_scheme: 
    - RileyLink
script:
    # We need to enumerate these manually until xctool is fixed
    - xcodebuild -project RileyLink.xcodeproj -scheme RileyLink -sdk iphonesimulator9.3 test
    - xcodebuild -project RileyLink.xcodeproj -scheme RileyLink -sdk iphonesimulator9.2 test
